### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by PinetreePantry** [loganriggs/sae-rm#1]
I played around with `custom_prompts.ipynb`. Found that the method signatures defined in interp_utils is different from that assumed in the notebook. In particular, `feature_activations, reward = get_autoencoder_activation(model, activation_name, tokens, sae)` implies that `get_autoencoder_activation` should return two values (one of them is reward), but the `get_autoencoder_activation` in interp_utils only return a single value.

**Comment by loganriggs** [comment]
You're correct. Thanks! I had some older interp_utils up, but I was able to replicate the original notebook display now (along w/ the html display which also was old). 

I'v additionally added some more comments to custom_prompts & a quicker way to display custom prompts reward & reward difference.
